// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int i = 0;
		int bigger = 0;
		int smaller = 0;
		double result = 0;
		double ratio = 0;
		while (i < N){
			result = Math.random();
			if (result > 0.5){
				bigger++;
			}
			else{
				smaller++;
			}
			i++;
		}
		if ((bigger == N) || (smaller == N)){
			System.out.println("> 0.5: " + bigger + " times");
			System.out.println("<= 0.5: " + smaller + " times");
		}
		else {	
			if (bigger > smaller){
				ratio = (double) smaller / (double) bigger;
			}
			else {
				ratio = (double) bigger / (double) smaller;
			}
			System.out.println("> 0.5: " + bigger + " times");
			System.out.println("<= 0.5: " + smaller + " times");
			System.out.print("Ratio: " + ratio);
		}
	}
}
